#!/usr/bin/env php
<?php
use App\SampleCommand;
use Symfony\Component\Console\Application;

$_ENV['HOME'] = getenv('HOME');

require __DIR__.'/vendor/autoload.php';

$app = new Application('php-cli-sample', '0.1');

$app->add(new SampleCommand);
$app->run();